### ISSUE TITLE
Still up to date?

### ISSUE THREAD

**Issue by FrankBoesing** [PaulStoffregen/arm_math#2]
Hi Paul, is this the currently used version? I'd like to compile it with a newer GCC.

**Comment by PaulStoffregen** [comment]
sorry, don't remember - it's been a long time and right now I'm overloaded on cryptography stuff

**Comment by FrankBoesing** [comment]
I've compiled the files with GCC10.3, added CM7. 
The binary files are in the GCC10 subfolder. 
A modified makefile is in the Windows subfolder.

https://github.com/FrankBoesing/arm_math
