### ISSUE TITLE
Source matrix modified by arm_mat_inverse

### ISSUE THREAD

**Issue by luistope** [PaulStoffregen/arm_math#3]
Hello, 
I have an algorithm using arm_math_inverse. 
In one operation I reuse the input operand passed to arm_mat_inverse.

arm_mat_inverse(&SumCk, &InvSumCk); // SumCk value changes in the inverse operation
arm_mat_mult(&SumCk, &Dk, &result);   // Bad result because SumCk doesn't have his original value

arm_status arm_mat_inverse_f32(**const** arm_matrix_instance_f32 * pSrc,  arm_matrix_instance_f32 * pDst)
The pSrc parameter is declared as const. The pSrc value never would change.

The algorithm performs a sequence of elementary row operations till it reduces the input matrix to an identity matrix.
The input matrix changes. 

Is there any other arm_mat_ function that changes the input parameters?
Thank you

**Comment by FrankBoesing** [comment]
Hi luistope, 

this lib is written by ARM - not PJRC, so it's best to lokk at their documentation which is included in the DOC subdirectory. Best is to use the doc included in this version (3.01), as it is from 2012. ( compare whith: [https://arm-software.github.io/CMSIS_5/General/html/cm_revisionHistory.html](https://arm-software.github.io/CMSIS_5/General/html/cm_revisionHistory.html) ) Or ask in a ARM forum
